### ISSUE TITLE
If I download an .html file it becomes zipped

### ISSUE THREAD

**Issue by kari-hardarson** [devopshq/artifactory#297]
I use this code:
```
def download_file(path,fn):
    with path.open() as fd, open(fn, "wb") as out:
        out.write(fd.read())
    return fn
```
to download  an .html file from Artifactory.  When I open the resulting file, it is zipped!
If I rename it to "foo.html.zip", I can open it and the real html file is inside the .zip file.

**Comment by beliaev-maksim** [comment]
@kari-hardarson 
can you try:
~~~python
def download_file(path,fn):
    path.writeto(fn)
    return fn

~~~

**Comment by kari-hardarson** [comment]
This fixed my problem!  Thank you.  Am I correct in assuming I hit upon a bug?

Best regards, Kari

**Comment by beliaev-maksim** [comment]
unfortunately, I cannot reproduce the issue. This might be somehow related to Artifactory settings. The only difference between your and one that I provided, is that content is downloaded in chunks instead of raw. However, knowing the background of requests, raw is also done in chunks

so, at this moment it does not worth to investigate the issue that I cannot reproduce.
