### ISSUE TITLE
Usage examples seems to be out dated

### ISSUE THREAD

**Issue by dothque** [devopshq/artifactory#305]
the usage examples starts with 
`from artifactory import ArtifactoryPath`

which does not exists after 
`pip install dohq-artifactory `

I tried to use 
`from dohq_artifactory import ArtifactoryPath`
but this one does not have ArtifactoryPath.

**Comment by HWiese1980** [comment]
I have just run into the same problem. I installed `dohq-artifactory==0.8.3` (exact entry) through a `requirements.txt` from PyCharm. Somehow it installed a package named `dohq_artifactory` (underscore instead of dash) which did not contain the `artifactory.py`. At least that is what I'm assuming after `pip uninstall dohq-artifactory` did not work, however `pip uninstall dohq_artifactory` did. After I uninstalled it via `pip uninstall dohq_artifactory` and reinstalled it via `pip install -r requirements.txt` and now it works. 

I have no idea what went wrong during the PyCharm install.
